# Generated by Django 4.2.2 on 2023-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='isOrderd',
            field=models.BooleanField(default=False),
        ),
    ]
